import 'dart:io';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';
import 'package:excel/excel.dart';

import 'package:expense_tracker/core/database/database_helper.dart';
import 'package:expense_tracker/services/export_import_service.dart';

void main() {
  setUpAll(() {
    TestWidgetsFlutterBinding.ensureInitialized();
    sqfliteFfiInit();
    databaseFactory = databaseFactoryFfi;

    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(
      const MethodChannel('plugins.flutter.io/path_provider'),
      (MethodCall methodCall) async {
        return '.';
      },
    );
  });

  group('Excel Importer Verification Tests', () {
    final dbHelper = DatabaseHelper.instance;

    setUp(() async {
      await dbHelper.clearAllData();
    });

    test('Excel decoder correctly decodes sheets, rows, and text values without crashing', () {
      final excel = Excel.createExcel();
      final sheet = excel['Sheet1'];

      sheet.appendRow([
        TextCellValue('Date'),
        TextCellValue('Category'),
        TextCellValue('Expense'),
        TextCellValue('Amount'),
      ]);

      sheet.appendRow([
        TextCellValue('2026-08-27'),
        TextCellValue('Groceries'),
        TextCellValue('Milk'),
        DoubleCellValue(1500.0),
      ]);

      final bytes = excel.encode()!;
      expect(bytes, isNotEmpty);

      final decoded = Excel.decodeBytes(bytes);
      final decodedSheet = decoded.tables['Sheet1']!;
      expect(decodedSheet.rows.length, equals(2));

      final headerRow = decodedSheet.rows[0];
      final dataRow = decodedSheet.rows[1];

      expect(headerRow[0]?.value, isNotNull);
      expect(dataRow[3]?.value, isNotNull);
    });

    test('Export to Excel and verify generated bytes can be decoded', () async {
      final tempDir = Directory.systemTemp.createTempSync('excel_test_');
      final path = await ExportImportService.exportToExcel(customFolderPath: tempDir.path);
      expect(path, isNotNull);
      expect(File(path!).existsSync(), isTrue);
      tempDir.deleteSync(recursive: true);
    });
  });
}
